# Generated by Django 4.2.1 on 2023-09-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_article_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='company_logos/')),
                ('description', models.TextField()),
                ('video_url', models.URLField()),
                ('year_founded', models.PositiveIntegerField()),
                ('history', models.TextField()),
                ('requisites', models.TextField()),
            ],
        ),
    ]
