# Generated by Django 4.2.1 on 2023-09-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='short_content',
            field=models.CharField(default='ssf', max_length=300),
            preserve_default=False,
        ),
    ]
