# Generated by Django 4.2.1 on 2023-09-22 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_faq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={},
        ),
    ]
