# Generated by Django 4.2.1 on 2023-09-22 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='cake.png', upload_to='contacts/'),
            preserve_default=False,
        ),
    ]
