# Generated by Django 4.2.1 on 2023-09-26 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_quote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
