# Generated by Django 4.2.1 on 2023-11-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_delete_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adv_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='advertisement')),
                ('link', models.CharField(max_length=200)),
            ],
        ),
    ]
